name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm install
          npm install mocha chai sinon supertest --save-dev

      - name: Build Project
        run: |
          npm start

      - name: Run Unit Tests
        run: |
          npm run test

      - name: Update Project Code
        run: |
          git add .
          git commit -m "CI: Update project code"
          git push
